# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='chapter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='part',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
